from __future__ import annotations

from typing import Any

from sentinel_pipeline.models.graph import FlowGraph
from sentinel_pipeline.models.insight import Insight, Severity, Tier
from sentinel_pipeline.models.span import SpanKind
from sentinel_pipeline.signals.extractor import Signals
from .base import Detector


def _contains_string(value: Any, target: str) -> bool:
    """Recursively checks if the target string is present in any nested attribute values."""
    if isinstance(value, str):
        return target in value
    if isinstance(value, dict):
        return any(_contains_string(v, target) for v in value.values())
    if isinstance(value, (list, tuple, set)):
        return any(_contains_string(v, target) for v in value)
    return False


class UnusedLlmOutputDetector(Detector):
    id       = "unused_llm_output"
    name     = "Unused LLM Output"
    severity = Severity.WARNING
    tier     = Tier.FREE

    def evaluate(self, graph: FlowGraph, signals: Signals) -> list[Insight] | None:
        llm_spans = [s for s in graph.nodes.values() if s.kind == SpanKind.LLM_CALL]
        if not llm_spans:
            return None

        insights: list[Insight] = []
        for llm_span in llm_spans:
            # 1. Retrieve the output text generated by the LLM
            output_raw = llm_span.attributes.get("gen_ai.output")
            if not output_raw:
                continue
            output_text = str(output_raw).strip()
            
            # Skip empty or trivially short outputs to avoid false positives
            if len(output_text) < 10:
                continue

            # 2. Check if the workflow continued after this LLM call
            subsequent_spans = [
                s for s in graph.nodes.values()
                if s.span_id != llm_span.span_id and s.start_time >= llm_span.end_time
            ]
            if not subsequent_spans:
                continue

            # 3. Check if the output was referenced in any other span's attributes
            referenced = False
            for other_span in graph.nodes.values():
                if other_span.span_id == llm_span.span_id:
                    continue
                if _contains_string(other_span.attributes, output_text):
                    referenced = True
                    break

            # 4. If there were subsequent steps but the LLM output was never used, fire
            if not referenced:
                insights.append(Insight(
                    workspace_id=graph.workspace_id,
                    trace_id=graph.trace_id,
                    detector_id=self.id,
                    severity=self.severity,
                    title="Unused LLM output",
                    detail=(
                        f"LLM call '{llm_span.name}' generated an output, but this output "
                        f"was never referenced by any other downstream or parent span in the trace. "
                        f"The generation cost ({llm_span.output_tokens or 0} output tokens) was wasted."
                    ),
                    recommendation=(
                        "Review your agent's control flow. If the output of this LLM call is "
                        "not needed for subsequent decisions or tool inputs, consider removing "
                        "the call entirely or refining the prompt to omit this output."
                    ),
                    affected_span_ids=[llm_span.span_id],
                    evidence={
                        "llm_span_id": llm_span.span_id,
                        "output_length": len(output_text),
                        "output_tokens": llm_span.output_tokens or 0,
                    },
                ))

        return insights or None
